"""new tables

Revision ID: 038e34c28bc6
Revises: 
Create Date: 2020-08-17 14:13:33.529322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038e34c28bc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppies')
    # ### end Alembic commands ###
